import React, { useState, useEffect } from 'react';
import OrderElement from '../../Components/OrderElement/OrderElement';
import {database} from '../../firebase';
import { useStateValue } from '../../StateProvider';
import classes from './Orders.module.css';

function Orders() {

    const [{ basket, user }, disaptch] = useStateValue();
    const [orders, setOrders] = useState([]);
    const [data, setData] = useState(false);

    const spinnerStyle = {
        width: "10rem",
        height: "10rem"
    };

    const spinner = (
        <div className="d-flex justify-content-center" >
            <div className="spinner-border" role="status" style={spinnerStyle}>
                <span className="sr-only">Loading...</span>
            </div>
        </div>
    );

    // run only once when this component is loaded
    useEffect(() => {
        if (user) {
            database
                .collection('users')
                .doc(user?.uid)
                .collection('orders')
                .orderBy('created', 'desc')
                .onSnapshot(snapshot => {
                    setOrders(snapshot.docs.map(doc => {
                        return {
                            id: doc.id,     // this id is auto-generated at time of payment = paymentIntent.id(generated by Stripe)
                            data: doc.data()   // will return ( basket, amount, createdTime )   -> stored at the time of successfull payment
                        }
                    }))
                });
                {setData(true)}
        } else {
            setOrders([]);
        }
        
    }, [user] //these braces makes sure that useEffect will only run when there is some change in user which is setup at Login time in App.js
    );
    
    return (
        <div>

            <h2 className={classes.Heading}>Orders</h2>
            {data == false ? spinner : null}
            <div className={classes.Order}>
                {orders?.map(order => {
                    return <OrderElement key={order.id} orderDetails={order} />
                })}
            </div>
        </div>
    )
}

export default Orders
